@api = http://localhost:3000/api/order/


### get all
GET {{api}}
Content-Type: application/json

### get by id
GET {{api}}/6279a6b3-8b69-480e-84fe-9d5271c54e96
Content-Type: application/json

### post
POST {{api}}
Content-Type: application/json

{
  "order": {
    "nameCs": "John Doe",
    "sendTime": {{$timestamp}},
    "orderTime":  {{$timestamp}},
    "desc": "Order of electronics including headphones and chargers.",
    "address": "123 Main St, Springfield, USA",
    "id_delivery": "a6ba1f1c-118b-433d-a7e6-5b4f2fccb70e",
    "nameDelivery": "Express Logistics",
    "phoneDelivery": "+1234567890",
    "priceDelivery": 4999,
    "id_payment": "bf4bd8ac-2676-40f2-a726-87ad5a92df9d",
    "totalPayment": 10499,
    "totalAll": 15498,
    "status": "Pending"
  },
  "orderProduct": [
  	{ "id_product": "039d03a1-87b7-465f-b569-d0c01edb1f44" },
  	{ "id_product": "a817ba4c-0743-4f27-a1e1-a1d1b69b9863" }
  ],
  "orderReceiver": {
	"name": "Alice Johnson",
	"address": "456 Elm Street, Springfield, USA",
	"phone": "+19876543210"
  }
}

### Update
PUT {{api}}/6f01f47e-acb5-41f8-85d2-f44de9fe99ea
Content-Type: application/json

{
  "order": {
    "nameCs": "John Doe update",
    "sendTime": {{$timestamp}},
    "orderTime":  {{$timestamp}},
    "desc": "Order of electronics including headphones and chargers.",
    "address": "123 Main St, Springfield, USA",
    "id_delivery": "a6ba1f1c-118b-433d-a7e6-5b4f2fccb70e",
    "nameDelivery": "Express Logistics",
    "phoneDelivery": "+1234567890",
    "priceDelivery": 4999,
    "id_payment": "bf4bd8ac-2676-40f2-a726-87ad5a92df9d",
    "totalPayment": 10499,
    "totalAll": 15498,
    "status": "Pending"
  },
  "orderProduct": [
  	{ "id_product": "039d03a1-87b7-465f-b569-d0c01edb1f44" },
  	{ "id_product": "a817ba4c-0743-4f27-a1e1-a1d1b69b9863" }
  ],
  "orderReceiver": {
	"name": "Alice Johnson",
	"address": "456 Elm Street, Springfield, USA",
	"phone": "+19876543210"
  }
}



### delete
DELETE {{api}}/6f01f47e-acb5-41f8-85d2-f44de9fe99ea
Content-Type: application/json

{}
