### get data Bank
GET http://localhost:3000/api/bank?id=all
Content-Type: application/json


### get data Bank by id
GET http://localhost:3000/api/bank?id=Ma_09_Un_Kr_Bi_1693367481941
Content-Type: application/json


### create data Bank
POST http://localhost:3000/api/bank
Content-Type: application/json

{
  "id": "Ma_09_Un_Kr_Bi_1693367481941",
  "hp": "test1",
  "no": "asdasdas",
  "nama": "mandiri",
  "lokasi": "Semrang",
  "keterangan": "orak jelas",
  "jenis": "Kredit"
}

###

### update data Bank
PUT http://localhost:3000/api/bank?id=Ma_09_Un_Kr_Bi_1693367481941
Content-Type: application/json

{
  "id": "Ma_09_Un_Kr_Bi_1693367481941",
  "hp": "test1",
  "no": "asdasdas",
  "nama": "mandiri",
  "lokasi": "Semrang",
  "keterangan": "orak jelas",
  "jenis": "Kredit"
}

### delete data Bank
DELETE http://localhost:3000/api/bank?id=Ma_09_Un_Kr_Bi_1693367481941
Content-Type: application/json

{}


