### get all
GET http://localhost:3000/api/orderan
Content-Type: application/json

### get by id
GET http://localhost:3000/api/orderan/asd
Content-Type: application/json

### post
POST http://localhost:3000/api/orderanSalah
Content-Type: application/json

{
  "id": "asdasd",
  "no": "string",
  "guna": "string",
  "ongkir": 3681802,
  "lokasi": "string",
  "kirim": "2023-07-04",
  "pesan": "2023-07-04",
  "penerima": "string",
  "pengirim": "string",
  "ekspedisi": "string",
  "hpPenerima": "string",
  "hpPengirim": "string",
  "keterangan": "string",
  "semuaHargaItem": 3681802,
  "alamatPenerima": "string",
  "namaPengiriman": "string",
  "semuaHargaOrderan": 3681802,
  "semuaHargaProduct": 3681802,
  "semuaProduct": [
    {
      "id": "asdasda",
      "img": "string",
      "harga": 3681802,
      "nama": "string",
      "jenis": "string",
      "jumlah": 3681802,
      "lokasi": "string",
      "keterangan": "string"
    }
  ],
  "total": 3681802,
  "status": "string",
  "totalBayar": 3681802,
  "totalHarga": 3681802,
  "waktuKirim": "2023-07-04",
  "totalPenjualan": 3681802,
  "typePembayaran": "string"
}

### Update
PUT http://localhost:3000/api/orderan/asd
Content-Type: application/json

{
  "alamatPenerima": "Alamat Penerima",
  "ongkir": 23,
  "id": "asd",
  "no": "Nso",
  "semuaHargaItem": 12312,
  "semuaHargaOrderan": 12312,
  "semuaHargaProduct": 12312,
  "lokasi": "Lokasi update",
  "ekspedisi": "Ekspedisi update",
  "guna": "Keterangan update",
  "hpPenerima": "Hp Penerima update",
  "hpPengirim": "Hp Pengirim update",
  "namaPengiriman": "Nama Travel update",
  "pengirim": "orang genah update",
  "keterangan": "sangat jelas update",
  "penerima": "Penerima update update",
  "kirim": "1999-07-01T00:00:00.000Z",
  "pesan": "1999-07-01T00:00:00.000Z",
  "semuaProduct": [
    {
      "harga": 42000,
      "id": "produk lagi1 asd",
      "img": "bagsus",
      "jumlah": 10,
      "jenis": "Itesm",
      "keterangan": "Esnak",
      "lokasi": "Ungsaran",
      "nama": "Tahu sBakso Rebus",
      "orderanId": "asd"
    },
    {
      "harga": 42000,
      "id": "produk lagi asd",
      "img": "bagsus",
      "jumlah": 10,
      "jenis": "Itesm",
      "keterangan": "Esnak",
      "lokasi": "Ungsaran",
      "nama": "Tahu sBakso Rebus",
      "orderanId": "asd"
    }
  ],
  "status": "Status",
  "total": 123,
  "totalBayar": 123,
  "totalHarga": 1231,
  "totalPenjualan": 232,
  "typePembayaran": "Pemsbayaran",
  "waktuKirim": "2023-07-20T00:00:00.000Z"
}


### delete
DELETE http://localhost:3000/api/orderan/data1
Content-Type: application/json

{
}
