### get data Produk
GET http://localhost:3000/api/produk

### get data Produk by id
GET http://localhost:3000/api/product/ba_20_Un_Or_Pe_1691217722289

### create data Produk`
POST http://localhost:3000/api/produk
Content-Type: application/json

{
  "id": "ss",
  "harga": 20000,
  "img": "tidak ada ",
  "jenis": "orderan",
  "jumlah": 86,
  "keterangan": "Pedas",
  "lokasi": "Semarang",
  "nama": "tahu baxo"
}


### update data Produk`
PUT http://localhost:3000/api/product/ba_20_Un_Or_Pe_1691217722289
Content-Type: application/json

{
  "nama": "tahu baxo update lagi 1x",
  "harga": 20000,
  "img": "tidak ada ",
  "jenis": "orderan",
  "jumlah": 1,
  "keterangan": "Pedas",
  "lokasi": "Semarang"
}

### delete data Produk`
DELETE http://localhost:3000/api/produk/Ta_20_Un_Or_Pe_1691166993320
