### get data Produk`
GET http://localhost:3000/api/produk/

### get data Produk` by id
GET http://localhost:3000/api/produk/ab4beff0-0ab5-4043-b7f6-c156a210da60

### create data Produk`
POST http://localhost:3000/api/produk
Content-Type: application/json

{
  "harga": 20000,
  "img": "tidak ada ",
  "jenis": "orderan",
  "jumlah": 1,
  "keterangan": "Pedas",
  "lokasi": "Semarang",
  "nama": "tahu baxo"
}


### update data Produk`
PUT http://localhost:3000/api/produk/ab4beff0-0ab5-4043-b7f6-c156a210da60
Content-Type: application/json

{
  "nama": "tahu baxo update",
  "harga": 20000,
  "img": "tidak ada ",
  "jenis": "orderan",
  "jumlah": 1,
  "keterangan": "Pedas",
  "lokasi": "Semarang"
}

### delete data Produk`
DELETE http://localhost:3000/api/produk/ab4beff0-0ab5-4043-b7f6-c156a210da60
