import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {

  return (
    <html lang="en" className={inter.className} data-theme={'dark'}>
      <body className={"min-h-screen "}>
        {children}
      </body>
    </html>
  )
}
