import { TPaymentCreate, TPaymentDB } from "@/interface/entity/payment.model"
import type { type } from "node:os"

export const examplePayment: TPaymentCreate = {
    // id        : "kosong",  // ID can be autogenerated or provided dynamically
    type: "Credit Card", // Example payment method type
    address: "123 Main St, Springfield, IL", // Billing address for payment
    desc: "Payment for order #12345", // Description of the payment
    accounting: "Transaction #98765", // Reference for accounting or tracking purposes
    phone: "+6234567890", // Contact phone number associated with the payment
    img: "https://example.com/payment-image.jpg", // Image URL related to payment method (optional)
    name: "John Doe", // Name of the person making the payment
}
export const formBank: Record<keyof TPaymentDB, any> = {
    phone: "No Telephone Perusahaan",
    name: "Nama Bank",
    accounting: "No Rekening",
    id: "123_bank",
    address: "Lokasi Bank",
    type: "Jenis Bank",
    desc: "Keterangan",
    img: "URL Gambar Logo perusahaan ",
    created_at: new Date(),
    updated_at: new Date(),
}
